'use client';

import { FormEvent, useState } from 'react';

export default function PublicReportForm() {
  const [form, setForm] = useState({ target_type: 'phone', target_name: '', incident_type: 'other', description: '', evidence_text: '' });
  const [file, setFile] = useState<File | null>(null);
  const [result, setResult] = useState('');
  function update(key: string, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setResult('Đang gửi...'); const response = await fetch('/api/v1/reports', { method: 'POST', headers: { 'content-type': 'application/json', 'x-idempotency-key': `web:${crypto.randomUUID()}` }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { setResult(data.error ?? 'Không thể gửi báo cáo'); return; } if (file) { const upload = new FormData(); upload.set('file', file); await fetch(`/api/v1/reports/${data.report.tracking_code}/attachments`, { method: 'POST', body: upload }); } setResult(`Đã tiếp nhận. Mã theo dõi: ${data.report.tracking_code}`); }
  return <main className="public-shell"><nav><a href="/">ScamShield</a><a href="/lookup">Tra cứu</a></nav><section className="form-card"><p className="eyebrow">COMMUNITY REPORT</p><h1>Gửi báo cáo</h1><p className="muted">Chỉ gửi thông tin bạn có căn cứ. Report sẽ được review trước khi hiển thị công khai.</p><form onSubmit={submit}><label>Loại đối tượng<select value={form.target_type} onChange={(event) => update('target_type', event.target.value)}><option value="phone">Số điện thoại</option><option value="bank_account">Tài khoản ngân hàng</option><option value="telegram_user">Telegram username</option><option value="website">Website</option><option value="crypto_wallet">Crypto wallet</option><option value="email">Email</option></select></label><label>Đối tượng<input value={form.target_name} onChange={(event) => update('target_name', event.target.value)} required /></label><label>Loại vụ việc<select value={form.incident_type} onChange={(event) => update('incident_type', event.target.value)}><option value="other">Khác</option><option value="ecommerce_scam">Mua bán online</option><option value="investment_scam">Đầu tư</option><option value="phishing">Phishing</option><option value="job_scam">Việc làm</option><option value="crypto_scam">Crypto</option></select></label><label>Mô tả sự việc<textarea value={form.description} onChange={(event) => update('description', event.target.value)} required minLength={20} /></label><label>Bằng chứng dạng text<textarea value={form.evidence_text} onChange={(event) => update('evidence_text', event.target.value)} placeholder="Link, mã giao dịch hoặc thông tin liên quan nếu có" /></label><label>File bằng chứng<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><button>Gửi báo cáo</button></form>{result && <p className="success">{result}</p>}</section></main>;
}
