'use client';

import { useEffect, useState } from 'react';
import { createBrowserSupabaseClient } from '@/lib/supabase/browser';

type CaseItem = { id: string; case_code: string; title: string; summary?: string; status: string; severity: string; updated_at: string };
type Detail = { case: CaseItem; reports: Array<{ report_id: string; scam_reports?: { tracking_code: string; target_name: string; status: string } }>; entities: Array<{ entity_id: string; scam_entities?: { display_name: string; risk_level: string } }> };

export default function CaseManagement() {
  const [items, setItems] = useState<CaseItem[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [status, setStatus] = useState(''); const [message, setMessage] = useState('');
  const client = () => createBrowserSupabaseClient(); async function headers() { const { data } = await client().auth.getSession(); return { authorization: `Bearer ${data.session?.access_token ?? ''}` }; }
  async function load() { const response = await fetch(`/api/admin/cases?status=${status}`, { headers: await headers() }); const result = await response.json(); setItems(result.cases ?? []); }
  async function open(id: string) { const response = await fetch(`/api/admin/cases/${id}`, { headers: await headers() }); setDetail(await response.json()); setMessage(''); }
  async function act(action: string) { if (!detail) return; const target = action === 'link_report' || action === 'link_entity' ? window.prompt('Nhập UUID cần liên kết') : undefined; if ((action === 'link_report' || action === 'link_entity') && !target) return; const response = await fetch(`/api/admin/cases/${detail.case.id}/action`, { method: 'POST', headers: { ...(await headers()), 'content-type': 'application/json' }, body: JSON.stringify({ action, target_id: target }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error); return; } setMessage('Đã cập nhật case'); await open(detail.case.id); await load(); }
  useEffect(() => { void load(); }, [status]);
  return <main className="admin-shell"><header className="topbar"><div><p className="eyebrow">SCAMSHIELD / INVESTIGATIONS</p><h1>Cases</h1></div><a href="/admin/inbox">Review Inbox</a></header><section className="toolbar"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Tất cả trạng thái</option><option value="open">Open</option><option value="investigating">Investigating</option><option value="confirmed">Confirmed</option><option value="monitoring">Monitoring</option><option value="closed">Closed</option></select><button onClick={() => void load()}>Refresh</button></section><div className="inbox-grid"><section className="queue">{items.map((item) => <button className={`report-row ${detail?.case.id === item.id ? 'selected' : ''}`} key={item.id} onClick={() => void open(item.id)}><span><strong>{item.case_code}</strong><small>{item.title}</small></span><span className="pill">{item.status}</span></button>)}</section><section className="detail">{detail ? <><p className="eyebrow">{detail.case.case_code}</p><h2>{detail.case.title}</h2><p>{detail.case.summary || 'Chưa có summary.'}</p><div className="facts"><div><span>Status</span><strong>{detail.case.status}</strong></div><div><span>Severity</span><strong>{detail.case.severity}</strong></div><div><span>Reports</span><strong>{detail.reports.length}</strong></div></div><article><h3>Linked reports</h3>{detail.reports.map((item) => <p className="history" key={item.report_id}>{item.scam_reports?.tracking_code} · {item.scam_reports?.target_name}</p>)}</article><article><h3>Linked entities</h3>{detail.entities.map((item) => <p className="history" key={item.entity_id}>{item.scam_entities?.display_name} · {item.scam_entities?.risk_level}</p>)}</article><div className="actions"><button onClick={() => void act('investigating')}>Investigating</button><button onClick={() => void act('pending_review')}>Pending review</button><button onClick={() => void act('confirmed')}>Confirmed</button><button className="secondary" onClick={() => void act('link_report')}>Link report</button><button className="secondary" onClick={() => void act('link_entity')}>Link entity</button><button className="danger" onClick={() => void act('closed')}>Close</button></div>{message && <p className="success">{message}</p>}</> : <div className="empty"><h2>Chọn case</h2></div>}</section></div></main>;
}
